version: '3'
services:
  database:
    container_name: postgres-csc2020
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - C:\Users\SST Computer Lab/data/postgres/csc2020:/data/postgres
    env_file:
      - csc2020.env

